sudo: false
language: ruby
cache: bundler
rvm:
  - 2.5.1
before_install: gem install bundler -v 1.16.2
notifications:
  slack:
    secure: "mGQbIr0NYMp8nm+WmwXL4vt5l9KH7ykPdvYc4Ak2imimjtU6hUyk14d96xPclkoP1vW18pTu9+F9uVJUeV04AVGCPPFqyKtwGVTmNbKOWkCbESmRVD6B3Cxq/BOrNZJX61z45WIXyT2Exw2e5O7MG9Zk0rmWiLBZXl/K3bn+l5AIrMcavX6obLsdga2RVlM6o4AoecWAxYqXRGog+bcOSEK1k4mQbtSw/RlN76QVPA7nCqLe+wSilNvLBBFms+PdiWdHoTjx8Ks8WDRePUGhO062t5i7qZlcAkCPx0CI39C3CK2TK/2+UfqHh5EFpYARGmQ6csvP84ACexGB87enXtIaYd1GB8BTc25vwifMZydYn6+dYHzmYgnSyVu3UIr4GOgoCNpnDdFad4Xw9zDNDCQwNxQzJb6TKp0L37hAptVn2agix8J/Zx0yPRezzwFycREDK63S5UhF8md3E7WLQH9LaBN2NxBcku1VnKVOJ5PrQ4ckuEqUXWkfH0ntmFGD0y2uvt9mzkT7FkGIlsLenMgNuDS3eULWhi60AVibZJpSzedOfoVpWSYpG2FFg63oXNIjN3Pf6eI7eKo3K1QEbuBWmwk7+NUTlxBR8kcOf5YhW1rFqIDk5e0IGCxN0HD7dP9f19ZyrYPJzOZm7MwkFDFZ5cIUaBiahjBa9YkdU0M="
deploy:
  provider: rubygems
  gem: getto-params
  on:
    tags: true
  api_key:
    secure: "U089eNM+M344nDmn4liBEjPuScKV2KFzdoC4Ax1fyaM9knrYmOCleFJdr6QRDpxq+CDgrIqgqza9x5GAh73LWaEgzUScKUj56zvR2D5Zto7eRZW1ZSR1w4pKUnMDALN9uO5HjYVqHsKAxk6bbARldAmX3JbpsSAokWEvSxj5ZwmoIXH8f6XTrfRInDbLHvSYYJCg6oUUmGIqyPRw3pUrVAkdoGoy4fEbmxexyHUPuPH0Gj6qDEIxn8RLEk4sOf6zNIlD46zLOnJjLaBh6jGferRvvEv9eUfi6CWppsGXlQz08D2CrL1FMBFHN3oAYOOjTv2y6nEgdM1KJevBCir+bob1Hq7D/OdoiYQB83PIuXKZ0ODXtXF05nEkThKS6eX+gUsTM4C3BJOq8lt/QbT7LePpCrWq/iBbFysyfTiFtCj23+vUAXv/rkxbthxC954oqDR9INY76hAOYHKgiz9vG61SqVZMMpCM/A7KJw7haNpmaYANCpskBANxaFk34BPXMYV4U2xJJy/2YHPTbLTwSjjpAUiRM6lZZSocB/ltONNK9sG+Nupxmx/LU60DsArAzKC2P+SFYOx53/mb3kneJBiNZG2YoLXAd7MshBdTKmfk2pox3QD6JcYWC5Lt7dD1cSgh9KtX69ak7hag/Q0x4xWn6mDI9i+L/9I3Oo0Fecc="
